# Generated by Django 3.1.4 on 2021-01-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=2000, verbose_name='Описание')),
                ('ddate', models.DateTimeField(verbose_name='Дата сбора')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Код')),
                ('num', models.IntegerField(blank=True, verbose_name='Номер')),
            ],
        ),
    ]
