# Generated by Django 3.1.4 on 2021-01-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='station',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
    ]
