# Generated by Django 3.1.4 on 2021-01-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20210104_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('eng_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Английское наименование')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код')),
                ('descr', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('descr_st', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание станций')),
                ('descr_worm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание червей')),
            ],
        ),
    ]
