# Generated by Django 3.1.4 on 2021-01-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_ship'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
        migrations.AlterModelTable(
            name='ship',
            table='ship',
        )
    ]
