# Generated by Django 3.1.4 on 2021-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_family'),
    ]

    operations = [
            migrations.AlterField(
            model_name='family',
            name='family',
            field=models.CharField('Семейство', max_length=255, unique=True),
        ),
    ]
