# Generated by Django 3.1.4 on 2021-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_family'),
        ('station', '0007_auto_20210203_1626'),
        ('station', '0008_genus'),
    ]

    operations = [
            migrations.AlterField(
            model_name = 'genus',
            name = 'family_name',
            field = models.ForeignKey('family', on_delete=models.CASCADE, verbose_name='Семейство', related_name='genus_name'),
        ),
    ]
