# Generated by Django 3.1.4 on 2021-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_species'),
        ('station', '0006_family'),
        ('station', '0007_auto_20210203_1626'),
        ('station', '0008_genus'),
        ('station', '0009_auto_20210203_1731'),
    ]

    operations = [
            migrations.AlterField(
            model_name = 'species',
            name = 'genus_name',
            field = models.ForeignKey('genus', on_delete=models.CASCADE, verbose_name='Родовое название'),
        ),
            migrations.AlterField(
            model_name = 'species',
            name = 'family',
            field = models.ForeignKey('family', on_delete=models.CASCADE, verbose_name='Семейство'),
        ),
    ]
