# Generated by Django 3.1.4 on 2021-02-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0010_auto_20210203_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
    ]
